name: protein-func
channels:
  - defaults
  - conda-forge
  - pyg
dependencies:
  - python=3.10
  - scikit-learn
  - tensorboard
  - numpy
  - h5py
  - pandas
  - pytorch
  - pyg
  - pip
  - pip:
    - biopython
    - matplotlib
    - networkx
    - h5py
