name: protein-func
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn
  - tensorboard
  - numpy
  - h5py
  - pandas
  - pytorch
  - pytorch-cuda=12.4
  - pyg
  - pip
  - pip:
    - biopython
    - matplotlib
    - networkx
    - h5py
